### ISSUE TITLE
我的node 版本v0.10.25，报了SyntaxError: Use of const in strict mode的错误，该怎样解决？

### ISSUE THREAD

**Issue by WeihuaGu** [magicdawn/yun-playlist-downloader#13]
具体如下：
```
yun -c 10 https://music.163.com/#/playlist?id=523729488

/usr/local/lib/node_modules/yun-playlist-downloader/bin/yun:5
const path = require('path')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by magicdawn** [comment]
![image](https://cloud.githubusercontent.com/assets/4067115/21376162/be5f45b6-c76d-11e6-815a-d577ed99b678.png)

**Comment by magicdawn** [comment]
node v6 已是最新 LTS, 建议升级至 v6

**Comment by WeihuaGu** [comment]
@magicdawn 谢谢你。我升级再看看。
