### ISSUE TITLE
跑不起来啊，好像不是Electron没安装好啊

### ISSUE THREAD

**Issue by 4698to** [magicdawn/yun-playlist-downloader#14]
C:\Users\Administrator>yun
C:\Users\Administrator\AppData\Roaming\npm\node_modules\yun-playl
node_modules\electron\index.js:9
  throw new Error('Electron failed to install correctly, please d
les/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_m
 and try installing again
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming
es\yun-playlist-downloader\node_modules\electron\index.js:9:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming
es\yun-playlist-downloader\node_modules\nightmare\lib\nightmare.j
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by magicdawn** [comment]
Electron failed to install correctly, please delete node_modules
and try installing again

**Comment by raypp** [comment]
Magicdawn兄，
我也遇到同样的问题了，重新安装了electron也不行。错误信息同上。

**Comment by magicdawn** [comment]
升级了下依赖 nightmare 2.8 -> 2.9, 对 Electron 的依赖方式有更改.
可以安装最新版本试试. 还有问题请反馈. 谢谢.
