### ISSUE TITLE
install的时候出现一个异常

### ISSUE THREAD

**Issue by ilulu** [magicdawn/yun-playlist-downloader#21]
hi 大神，昨天clone下来的源码在 npm install 的时候会出一个异常
```
79 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...oli-uglify-js":"^0.2.'
79 verbose stack     at JSON.parse (<anonymous>)
79 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
79 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
79 verbose stack     at <anonymous>
79 verbose stack     at process._tickCallback (internal/process/next_tick.js:160:7)
```

另外还有一行显示如下
```
silly fetchPackageMetaData error for es6-promise@4.1.1 Unexpected end of JSON input while parsing near '...oli-uglify-js":"^0.2.'
```

呃，我这里为了速度把npm的源设置为了淘宝，会不会是这个原因。拜谢

**Comment by ilulu** [comment]
大神打扰了，果然是万恶的淘宝镜像的原因，拜谢
