### ISSUE TITLE
无法修改音乐下载路径，而且只有给予root权限后，才能运行

### ISSUE THREAD

**Issue by oldzhg** [magicdawn/yun-playlist-downloader#22]
系统环境：MacBook Air， OS X 10.13.2

如果在普通用户下执行，部分报错如下：
```
⚠ 15/19  1次失败 /Richard Clayderman - Mariage d'amour.mp3
⚠ 15/19  2次失败 /Richard Clayderman - Mariage d'amour.mp3
⚠ 15/19  3次失败 /Richard Clayderman - Mariage d'amour.mp3
✖ 15/19 下载失败 /Richard Clayderman - Mariage d'amour.mp3
Error: tried function <anonymous> 3 times with timeout = 180000ms
    at /usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.retry/index.js:61:11
    at Generator.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/co/index.js:81:24)
    at <anonymous>

```

无论当前位于哪个目录，获取root权限后下载位置始终为根目录 / 下

**Comment by magicdawn** [comment]
无法重现...

**Comment by qq270755744** [comment]
这能不能下载付费音乐

**Comment by magicdawn** [comment]
不能

**Comment by AaronLiang** [comment]
不能下载付费音乐 那这个东西的目的是？
