### ISSUE TITLE
好像用不了？

### ISSUE THREAD

**Issue by ajaxsys** [magicdawn/yun-playlist-downloader#3]
你好，试了一下，好像出问题了。能否看一下。

$ yun
module.js:338
    throw err;
    ^

Error: Cannot find module 'superagent/node_modules/cookiejar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js:4:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yun-playlist-downloader/bin/yun:7:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

安装时候没问题，版本和log如下：
node v4.0.0
npm  v3.3.3

$ npm i yun-playlist-downloader -g
/usr/local/bin/yun -> /usr/local/lib/node_modules/yun-playlist-downloader/bin/yun
/usr/local/lib
└─┬ yun-playlist-downloader@0.1.0
  ├── bluebird@2.10.0
  ├─┬ cheerio@0.19.0
  │ ├─┬ css-select@1.0.0
  │ │ ├── boolbase@1.0.0
  │ │ ├── css-what@1.0.0
  │ │ ├── domutils@1.4.3
  │ │ └── nth-check@1.0.1
  │ ├─┬ dom-serializer@0.1.0
  │ │ └── domelementtype@1.1.3
  │ ├── entities@1.1.1
  │ └─┬ htmlparser2@3.8.3
  │   ├── domelementtype@1.3.0
  │   ├── domhandler@2.3.0
  │   ├── domutils@1.5.1
  │   ├── entities@1.0.0
  │   └── readable-stream@1.1.13
  ├── co@4.6.0
  ├── crypto-js@3.1.5
  ├── lodash@3.10.1
  ├── minimist@1.2.0
  ├─┬ superagent@1.4.0
  │ ├── component-emitter@1.1.2
  │ ├── cookiejar@2.0.1
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── extend@1.2.1
  │ ├─┬ form-data@0.2.0
  │ │ ├── async@0.9.2
  │ │ ├─┬ combined-stream@0.0.7
  │ │ │ └── delayed-stream@0.0.5
  │ │ └─┬ mime-types@2.0.14
  │ │   └── mime-db@1.12.0
  │ ├── formidable@1.0.14
  │ ├── methods@1.0.1
  │ ├── mime@1.3.4
  │ ├── qs@2.3.3
  │ ├─┬ readable-stream@1.0.27-1
  │ │ ├── core-util-is@1.0.1
  │ │ ├── inherits@2.0.1
  │ │ ├── isarray@0.0.1
  │ │ └── string_decoder@0.10.31
  │ └── reduce-component@1.0.1
  └── superagent-bluebird-promise@2.1.0

**Comment by magicdawn** [comment]
看下 `/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/cookiejar` 文件夹存在么

**Comment by magicdawn** [comment]
或者使用新版本 v0.2.0 , 再次运行 `npm i yun-playlist-downloader -g` 即可
新版本直接依赖 `cookiejar`
