### ISSUE TITLE
Catalina 安装失败

### ISSUE THREAD

**Issue by zzzDavid** [magicdawn/yun-playlist-downloader#33]
## 系统
- Catalina 10.15
- xcode-select version 2370
- nodejs v12.13

## 报错信息
```
> get-cursor-position@1.0.3 install /Users/zhangniansong/node_modules/get-cursor-position
> node-gyp rebuild

  CXX(target) Release/obj.target/pos/src/pos.o
../src/pos.cc:272:22: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
                     ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2934:10: note: 'NewFromUtf8' has been explicitly marked
      deprecated here
  static V8_DEPRECATED(
         ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:272:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
         ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:273:22: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
                     ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2934:10: note: 'NewFromUtf8' has been explicitly marked
      deprecated here
  static V8_DEPRECATED(
         ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:273:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
         ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:277:6: error: variable has incomplete type 'void'
void Init(Handle<Object> exports) {
     ^
../src/pos.cc:277:11: error: use of undeclared identifier 'Handle'
void Init(Handle<Object> exports) {
          ^
../src/pos.cc:277:18: error: 'Object' does not refer to a value
void Init(Handle<Object> exports) {
                 ^
/Users/zhangniansong/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3400:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/pos.cc:277:26: error: use of undeclared identifier 'exports'
void Init(Handle<Object> exports) {
                         ^
../src/pos.cc:277:34: error: expected ';' after top level declarator
void Init(Handle<Object> exports) {
                                 ^
                                 ;
4 warnings and 5 errors generated.
make: *** [Release/obj.target/pos/src/pos.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhangniansong/node_modules/get-cursor-position
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/zhangniansong/package.json'
npm WARN zhangniansong No description
npm WARN zhangniansong No repository field.
npm WARN zhangniansong No README data
npm WARN zhangniansong No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-cursor-position@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get-cursor-position@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangniansong/.npm/_logs/2019-10-27T17_24_11_725Z-debug.log

```

**Comment by zzzDavid** [comment]
重新安装了老版本的Node.js解决了这个问题
