### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by liujiaxian** [magicdawn/yun-playlist-downloader#36]
/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/yargs/node_modules/find-up/index.js:29
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at pkgUp (/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/yargs/yargs.js:570:20)
    at guessVersion (/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/yargs/yargs.js:900:17)

**Comment by magicdawn** [comment]
使用 Node.js 当前 LTS 版本 12.x 即可
