### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by flicat** [magicdawn/yun-playlist-downloader#39]
当前参数
concurrency:    5
format:         :name/:singer - :songName.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true

ReferenceError: URL is not defined
    at exports.getId (C:\Users\Lee\AppData\Roaming\npm\node_modules\yun-playlist-downloader\lib\util.js:45:13)
    at AlbumAdapter.getId (C:\Users\Lee\AppData\Roaming\npm\node_modules\yun-playlist-downloader\lib\adapter\base.js:27:12)
    at AlbumAdapter.getDetail (C:\Users\Lee\AppData\Roaming\npm\node_modules\yun-playlist-downloader\lib\adapter\album.js:11:21)
    at exports.getSongs (C:\Users\Lee\AppData\Roaming\npm\node_modules\yun-playlist-downloader\lib\index.js:209:29)
    at main (C:\Users\Lee\AppData\Roaming\npm\node_modules\yun-playlist-downloader\bin\yun:141:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

大佬，哪里不对吗？

**Comment by flicat** [comment]
node 版本是 v8.11.2

**Comment by magicdawn** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/url.html#url_class_url


v10.0.0 | The class is now available on the global object.
-- | --
v7.0.0, v6.13.0 | Added in: v7.0.0, v6.13.0


需要 node.js > 10 推荐使用 最新 LTS 12.x 版本
