### ISSUE TITLE
缺少依赖

### ISSUE THREAD

**Issue by lifeike** [magicdawn/yun-playlist-downloader#43]
小老弟，阔以哟，这个东西很方便哟，不过第一次用报错了
Ubuntu 20.04
npm 8.1.2
nodejs 10.19.0

1. 下载专辑提示缺少依赖

`
当前参数
concurrency:    5
format:         :name/:singer - :songName.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true
cover:          false

正在下载『舞剧《李白》音乐（完整版）』,请稍候...
ℹ 可下载 24/24 首
Error: Cannot find module '@magicdawn/ascii-progress'
Require stack:
- /usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js
- /usr/local/lib/node_modules/yun-playlist-downloader/lib/bin.js
- /usr/local/lib/node_modules/yun-playlist-downloader/bin/yun
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.downloadSongWithProgress (/usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js:41:25)
    at Object.exports.downloadSong (/usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js:34:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/yun-playlist-downloader/lib/bin.js:162:24)
    at /usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.map/src/index.js:29:30
    at replenish (/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.map/src/index.js:38:11)
    at /usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.map/src/index.js:40:7`

2. 试图自己安装依赖 npm i @magicdawn/ascii-progress

```
npm ERR! code 1
npm ERR! path /home/feeco/Desktop/test/node_modules/@magicdawn/get-cursor-position
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/home/feeco/Desktop/test/node_modules/@magicdawn/get-cursor-position/build'
npm ERR!   CXX(target) Release/obj.target/pos/src/pos.o
npm ERR!   SOLINK_MODULE(target) Release/obj.target/pos.node
npm ERR! make: Leaving directory '/home/feeco/Desktop/test/node_modules/@magicdawn/get-cursor-position/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/feeco/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/feeco/Desktop/test/node_modules/@magicdawn/get-cursor-position/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/feeco/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/feeco/.cache/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/feeco/.cache/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/feeco/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/feeco/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/feeco/Desktop/test/node_modules/@magicdawn/get-cursor-position',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/pos.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Method(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/pos.cc:244:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
npm ERR!   244 |     int ret, row, col;
npm ERR!       |         ^~~
npm ERR! In file included from ../src/pos.cc:2:
npm ERR! ../src/pos.cc: At global scope:
npm ERR! /home/feeco/.cache/node-gyp/16.13.1/include/node/node.h:821:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   821 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |                                           ^
npm ERR! /home/feeco/.cache/node-gyp/16.13.1/include/node/node.h:855:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!   855 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/pos.cc:266:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   266 | NODE_MODULE(hello, Init)
npm ERR!       | ^~~~~~~~~~~
npm ERR! /usr/bin/ld: Release/obj.target/pos/src/pos.o: relocation R_X86_64_PC32 against symbol `_Z6MethodRKN3Nan20FunctionCallbackInfoIN2v85ValueEEE' can not be used when making a shared object; recompile with -fPIC
npm ERR! /usr/bin/ld: final link failed: bad value
npm ERR! collect2: error: ld returned 1 exit status
npm ERR! make: *** [pos.target.mk:141: Release/obj.target/pos.node] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/feeco/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.11.0-43-generic
npm ERR! gyp ERR! command "/home/feeco/.nvm/versions/node/v16.13.1/bin/node" "/home/feeco/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/feeco/Desktop/test/node_modules/@magicdawn/get-cursor-position
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/feeco/.npm/_logs/2022-01-06T16_43_11_231Z-debug.log
```

**Comment by magicdawn** [comment]
-p false 关闭进度显示

**Comment by lifeike** [comment]
> -p false 关闭进度显示

好滴，感谢，肥肠感谢，问题已经解决，没毛病～～
