### ISSUE TITLE
下载【喜欢的音乐】，报错Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by nrbackback** [magicdawn/yun-playlist-downloader#51]
下载【喜欢的音乐】，就是这个歌单
<img width="408" alt="image" src="https://user-images.githubusercontent.com/102530911/200107886-9cc59e58-18ee-4137-98bb-1562d6bf8418.png">
按照要求安装了EditThisCookie插件并设置了cookie，导出的cookie是这样的格式，应该也没错：
```
// Semicolon separated Cookie File
// This file was generated by EditThisCookie
// Details: http://www.ietf.org/rfc/rfc2109.txt
// Example: http://www.tutorialspoint.com/javascript/javascript_cookies.htm
__bid_n=xxx;_ntes_nnid=xxx;
```
执行 `yun https://music.163.com/\#/playlist\?id\=xxx`报错了，报错内容如下：
```
当前参数
concurrency:    5
format:         :name/:singer - :songName.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true
cover:          false

[cookie] 使用 cookie 文件: /yun.cookie.txt
正在下载『小黑喜欢的音乐』,请稍候...
TypeError: Cannot read property 'map' of undefined
    at PlaylistAdapter.filterSongs (/usr/local/lib/node_modules/yun-playlist-downloader/lib/adapter/base.js:74:31)
    at PlaylistAdapter.getSongs (/usr/local/lib/node_modules/yun-playlist-downloader/lib/adapter/playlist.js:49:36)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async main (/usr/local/lib/node_modules/yun-playlist-downloader/lib/bin.js:145:19)
```
是什么设置错了吗或者没安装什么？不知道是不是和我的歌单歌曲数量太多有关，歌单里有两千多首，除此之外我也想不到什么特殊的地方了。

PS：还有另一个小问题，想下载的时候设置文件名中包含专辑名，比如
<img width="471" alt="image" src="https://user-images.githubusercontent.com/102530911/200108239-0d25fe79-425d-476a-9e43-5fd26b0decaa.png">
最后下载的文件名大概是`陈奕迅-U87-浮夸.mp3`这样，-f参数里能设置吗？我尝试设置了下-f发现都不生效，感谢回答

**Comment by magicdawn** [comment]
```
yun 'https://music.163.com/#/album?id=6491' -f ':name/:singer-:name-:songName.:ext'
```
![image](https://user-images.githubusercontent.com/4067115/201673137-2bfaec7f-48ca-443d-9afd-f20b08b31bad.png)

**Comment by magicdawn** [comment]
fixed in latest v3.2.1

![image](https://user-images.githubusercontent.com/4067115/201688313-478985ad-02d8-4c49-9e5c-5a41cff8a491.png)
