### ISSUE TITLE
Cannot read properties of undefined (reading 'sort')

### ISSUE THREAD

**Issue by cxiniao** [magicdawn/yun-playlist-downloader#63]
concurrency:    5
format:         :name/:singer - :songName.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        999k
skip:           true
progress:       true
cover:          false

[cookie] 使用 cookie 文件: D:\task\yunmusicdm\yun.cookie.txt
正在下载『张敬轩神级live』,请稍候...
D:\soft\nodejs\npm_global\node_modules\yun-playlist-downloader\node_modules\NeteaseCloudMusicApi\module\song_url.js:23
  result.sort((a, b) => {
         ^

TypeError: Cannot read properties of undefined (reading 'sort')
    at module.exports (D:\soft\nodejs\npm_global\node_modules\yun-playlist-downloader\node_modules\NeteaseCloudMusicApi\module\song_url.js:23:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async singleRequest (file:///D:/soft/nodejs/npm_global/node_modules/yun-playlist-downloader/dist/chunk-55JQJ5AH.js:247:17)

**Comment by magicdawn** [comment]
unable to reproduce
